export const PRICING_TIERS = [
  {
    id: 'hobby',
    name: 'Hobby',
    price: '$0',
    interval: 'month',
    description: 'For personal projects and trying out the platform.',
    features: [
      '20 Scraping Jobs/month',
      'Unlimited Chat History',
      'Unlimited Active Chats',
      'Chat Pinning & Renaming',
      '1GB Scraped Data Storage',
      'Standard Support',
    ],
    buttonText: 'Start for Free',
    variantId: null,
    maxScrapingJobs: 20,
    maxChatHistoryDays: null,
    maxActiveChats: null,
    maxDataStorageMB: 1024,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '$29',
    interval: 'month',
    description: 'For power users, freelancers, and teams who need more volume and speed.',
    features: [
      '250 Scraping Jobs/month',
      'Unlimited Everything from Hobby',
      '10GB Scraped Data Storage',
      'Faster, Prioritized Scraping Queues',
      'Priority Support',
      'API Access (Coming Soon)',
      'Team Collaboration (Coming Soon)',
    ],
    buttonText: 'Upgrade to Pro',
    variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PRO_VARIANT_ID,
    maxScrapingJobs: 250,
    maxChatHistoryDays: null,
    maxActiveChats: null,
    maxDataStorageMB: 10 * 1024,
  },
];
